-- 用户行为埋点表
CREATE TABLE public.user_action (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users,           -- 用户ID（登录用户）
  anonymous_id text NOT NULL,                   -- 匿名ID（未登录用户）
  email text,                                   -- 用户邮箱
  event_type text NOT NULL,                     -- 事件类型：login_click, send_code_click, chapter_click
  event_data jsonb,                             -- 事件附加数据（如章节号）
  user_agent text,                              -- 浏览器 User Agent
  browser text,                                 -- 浏览器名称
  browser_version text,                         -- 浏览器版本
  os text,                                      -- 操作系统
  os_version text,                              -- 操作系统版本
  device_type text,                             -- 设备类型：desktop, mobile, tablet
  screen_resolution text,                       -- 屏幕分辨率
  language text,                                -- 浏览器语言
  timezone text,                                -- 时区
  referrer text,                                -- 来源页面
  created_at timestamptz DEFAULT now()          -- 创建时间
);

-- 创建索引以提高查询性能
CREATE INDEX idx_user_action_user_id ON public.user_action(user_id);
CREATE INDEX idx_user_action_anonymous_id ON public.user_action(anonymous_id);
CREATE INDEX idx_user_action_event_type ON public.user_action(event_type);
CREATE INDEX idx_user_action_created_at ON public.user_action(created_at);
CREATE INDEX idx_user_action_browser ON public.user_action(browser);
CREATE INDEX idx_user_action_os ON public.user_action(os);
CREATE INDEX idx_user_action_device_type ON public.user_action(device_type);

-- 启用 RLS（行级安全）
ALTER TABLE public.user_action ENABLE ROW LEVEL SECURITY;

-- 允许所有人插入（用于埋点）
CREATE POLICY "Allow insert for all users" ON public.user_action
  FOR INSERT
  WITH CHECK (true);

-- 只允许用户查看自己的数据
CREATE POLICY "Users can view own data" ON public.user_action
  FOR SELECT
  USING (auth.uid() = user_id OR anonymous_id = current_setting('request.jwt.claims', true)::json->>'anonymous_id');
